### ISSUE TITLE
MIS group?

### ISSUE THREAD

**Issue by rapbhan** [amit0rana/betterKite#1]
Could you also please add a MIS/Intraday Group so that all intraday positions alone can be focussed when doing intraday. I knew we can use Kite search; but this script does a EXCELLENT Job!

Thank you for the efforts!

**Comment by amit0rana** [comment]
I didn't think anyone is using it so didn't notice this message :) coincidently today I lost some money because I placed a MIS order by mistake and wasn't aware of it so added few related feature.

Please upgrade to latest version 1.03, you can now filter and see all MIS positions. I will implement filters within MIS later i.e. MIS nifty only , MIS banknifty only etc. I will have to redo the whole dropdown grouping, will do after tomorrow's expiry.

For upgrading to next version see note on how to upgrade here: https://github.com/amit0rana/betterKite/blob/master/betterUpstox.md

**Comment by rapbhan** [comment]
Thank you! 👍

**Comment by amit0rana** [comment]
Get the latest 2.00 update, I introduced a new way to filter MIS positions.

There is also major update on how to create/delete custom strategies.
